---
- hosts: localhost
  gather_facts: False
  become: Yes
  tasks:
  - name: install apache2 
    apt:
      name: apache2
      state: present
    notify: 
      - restart apache2
  - name: install php modules
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - php
      - libapache2-mod-php
      - php-mysql
      - php-cli
    notify:
      - restart apache2
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted        
         
